"""
Module: Historical Backtest & Performance Attribution Engine

OBJECTIVE:
    Simulates the out-of-sample historical performance of the optimized portfolio.
    This module acts as the "Time Machine," taking the Point-in-Time target weights 
    generated by the Portfolio Optimizer and replaying history to calculate realized 
    returns, risk metrics, and trading costs.

METHODOLOGY:
    1. Strict Lag Enforcement & Survivorship Bias Prevention:
       Aligns Target Holdings at time T with Realized Returns at time T+1. 
       Utilizes a Left Join methodology coupled with a -100% return assumption for 
       missing future returns to safely penalize the model for holding assets that 
       are halted, delisted, or bankrupt.

    2. Precise Turnover Calculation (Drift-Adjusted):
       Calculates true physical turnover by adjusting for intra-month Portfolio Drift.
       Rather than naively comparing Target(T) to Target(T-1), it compares Target(T) 
       against the actual Drifted Weights at the end of T-1, capturing the exact 
       trading volume required to rebalance the portfolio.

    3. Macro Integration:
       Ingests localized Risk-Free Rate data (Fama-French) to calculate true 
       Excess Returns for risk-adjusted performance evaluation.

    4. Institutional Tearsheet Generation:
       Outputs a comprehensive scorecard delineating Arithmetic Returns (for Sharpe/IR 
       validity) and Geometric Returns (CAGR, representing true compounded wealth), 
       alongside Volatility, Tracking Error, and Maximum Drawdown.
"""

import os
import pandas as pd
import numpy as np

class BacktestEngine:
    """
    Evaluates the historical performance of the optimal portfolio.
    
    Attributes:
        start_date (pd.Timestamp): Date to begin the backtest (skips burn-in time).
        panel_path (str): Path to the merged panel data.
        holding_path (str): Path to the optimal holdings parquet file.
        rf_path (str): Path to the risk-free rate parquet file.
        backtest_output_path (str): Directory where the tearsheet and curve will be saved.
    """
    def __init__(self, 
                 panel_path: str, 
                 holding_path: str,
                 rf_path: str, 
                 backtest_output_path: str,
                 start_date = None, 
                 transaction_cost_bps=10):
        
        # Configuration
        self.start_date = start_date
        self.panel_path = panel_path 
        self.holding_path = holding_path
        self.rf_path = rf_path 
        self.backtest_output_path = backtest_output_path
        self.transaction_cost_bps = transaction_cost_bps
        self.tc_decimal = transaction_cost_bps / 10000.0  # Convert 10 bps to 0.0010

        # State Variables (The "Table of Contents")
        self.holdings = None
        self.returns = None
        self.rf_rate = None 
        # outputs
        self.performance = None
        self.turnover = None

    def load_data(self):
        # 1. Load holdings data generated by portfolio.py 
        # the name of the holding file depends on portfolio.py specifications 
        if not os.path.exists(self.holding_path):
            raise FileNotFoundError('optimal_holdings parquet file not found. Run portfolio.py first.')
        self.holdings = pd.read_parquet(self.holding_path)
        
        # 2. we need panel data to get return 
        if not os.path.exists(self.panel_path):
            raise FileNotFoundError('panel parquet file not found. Exiting...')
        panel = pd.read_parquet(self.panel_path)

        # we want to merge return data with our holdings 
        # as a safety check, first we need to make sure permno, date exist in panel data
        panel.reset_index(inplace = True)
        required_cols = ['permno', 'date', 'ret_monthly']
        missing_cols = [c for c in required_cols if c not in panel.columns]

        if missing_cols:
            raise KeyError(f"panel data missing columns: {missing_cols}. check merger.py")
        self.returns = panel[required_cols].copy()

        # 3. Clean up Types & Indexing 
        self.holdings.reset_index(inplace = True)

        # As safety check, ensure datetime type for date column in both datasets 
        self.holdings['date'] = pd.to_datetime(self.holdings['date'])
        self.returns['date'] = pd.to_datetime(self.returns['date'])

        # Now set and sort index again 
        self.holdings.set_index(['permno', 'date'], inplace = True)
        self.returns.set_index(['permno', 'date'], inplace = True)

        self.holdings.sort_index(inplace = True)
        self.returns.sort_index(inplace = True)

        print("holdings and returns data loaded")

        # 4. Fetch Risk-Free rate
        if os.path.exists(self.rf_path):
            self.rf_rate  = pd.read_parquet(self.rf_path)
        else:
            raise FileNotFoundError(f"The Fama French risk free rate file doesn't exist in {self.rf_path}")

    def run_backtest(self):
        """
        Calculates the time-series of portfolio returns.
        
        Args:
            self.start_date (str): Start trading from this date (e.g., '1995-01-01').
                              Useful to skip the "burn-in" period where rolling factors (like Beta) are zero.
        """
        print("Running Backtest Simulation...")
        
        # --- Step 1: Lag Management ---
        # Align Holdings(T) with Returns(T+1)
        # We shift returns backwards by -1 (bringing future returns to the current row)
        # so that Row T contains: Holdings(T) and Returns(T+1).

        self.returns.sort_index(level = ['permno', 'date'], inplace = True)
        self.returns['ret_future'] = self.returns.groupby('permno')['ret_monthly'].shift(-1)

        # Keep all holdings, even if the stock vanishes next month! so a left join
        df = self.holdings.join(self.returns[['ret_future']], how = 'left')

        # Drop the very last date of the entire backtest, because T+1 does not exist yet.
        last_date = df.index.get_level_values('date').max()
        df = df.query("date < @last_date").copy()        
        #df = df[df.index.get_level_values('date') < last_date]


        # Because Stata compounded the exit return into the final active month, 
        # any missing future return simply means the capital is in cash (0.0 return).
        df['ret_future'] = df['ret_future'].fillna(0.0)

        # --- Step 2: Apply Burn-In Period ---
        # To make alphas benchmark-neutral we needed to caluclate beta. 
        # To calcualte beta of each stock, we needed a minimum of 36 periods (months).
        # So for each stock, the first 36 months of data is missing 
                
        if pd.notnull(self.start_date): 
            self.start_date = pd.to_datetime(self.start_date)
            print(f"Applying Burn-in: Starting backtest from {self.start_date.date()}...")
            df = df.query("date >= @self.start_date")
        
        # --- Step 3: Calculate Portfolio Returns ---
        # Portfolio Return = Sum(Weight_i * Return_i)
        def calc_weighted_ret(group):
            port_ret = (group['h_portfolio'] * group['ret_future']).sum()
            bench_ret = (group['h_benchmark'] * group['ret_future']).sum()
            return pd.Series({'port_ret': port_ret, 'bench_ret': bench_ret})
        
        performance = df.groupby('date').apply(calc_weighted_ret)    

        # --- Step 4: Integrate Risk-Free Rate ---
        # Join RF data to the calculated performance series
        performance = performance.join(self.rf_rate, how = 'left').fillna(0)
        performance.sort_index(inplace=True)

        #****************************
        # --- Step 5: Calculate Turnover ---
        # Drifted_weight = Old Weight * (1 + Stock Return) / (1 + Gross Portfolio Return)
        df['port_ret'] = df.index.get_level_values('date').map(performance['port_ret'])
        df['h_port_drifted'] = df['h_portfolio'] * (1 + df['ret_future']) / (1 + df['port_ret'])

        # Shift the drifted weights forward by 1 month to compare with the NEW targets
        w_target = df['h_portfolio'].unstack(level='permno').fillna(0.0)
        w_drifted = df['h_port_drifted'].unstack(level='permno').infer_objects(copy=False).fillna(0.0).shift(1)
        
        # Calculate one-sided turnover
        self.turnover = (w_target - w_drifted).abs().sum(axis=1) / 2.0
        
        # --- Step 6: Apply Transaction Costs & Calculate Net Returns ---
        # The turnover at index `t` is traded at the end of month `t`.
        # Shift the turnover forward by 1 month so the fee penalizes month `t+1`'s return.
        tc_penalty = self.turnover.shift(1).fillna(0.0) * self.tc_decimal
        
        # Calculate the Net Portfolio Return
        performance['net_port_ret'] = performance['port_ret'] - tc_penalty
        
        # --- Step 7: Calculate Derived & Cumulative Metrics (Net of Fees) ---
        performance['active_ret'] = performance['net_port_ret'] - performance['bench_ret']
        performance['excess_ret'] = performance['net_port_ret'] - performance['rf']

        # Calculate Cumulative Wealth (Log-like growth)
        performance['cum_port'] = (1 + performance['net_port_ret']).cumprod()
        performance['cum_bench'] = (1 + performance['bench_ret']).cumprod()
        performance['cum_active'] = (1 + performance['active_ret']).cumprod()

        self.performance = performance
        return performance
    
        """
        # Calculate Derived Metrics
        performance['active_ret'] = performance['port_ret'] - performance['bench_ret']
        performance['excess_ret'] = performance['port_ret'] - performance['rf']

        # sort index just to make sure
        performance.sort_index(inplace = True)

        # Calculate Cumulative Wealth (Log-like growth)
        # (1+r_T) = (1+r1)(1+r2)...
        performance['cum_port'] = (1 + performance['port_ret']).cumprod()
        performance['cum_bench'] = (1 + performance['bench_ret']).cumprod()
        performance['cum_active'] = (1 + performance['active_ret']).cumprod()

        self.performance = performance

        # --- Step 5: Calculate Turnover ---
        # Turnover = (target_weight - drifted_weight) 
        # where
        # Drifted_weight = Old Weight * (1 + Stock Return) / (1 + Portfolio Return)

        df['port_ret'] = df.index.get_level_values('date').map(performance['port_ret'])
        df['h_port_drifted'] = df['h_portfolio'] * (1 + df['ret_future']) / (1 + df['port_ret'])

        # Shift the drifted weights forward by 1 month to compare with the NEW targets
        # (Because we rebalance at the END of the month, we compare Target(T) vs Drifted(T-1))
        w_target = df['h_portfolio'].unstack(level = 'permno').fillna(0.0)
        w_drifted = df['h_port_drifted'].unstack(level = 'permno').fillna(0.0).shift(1)
        
        # calculate turnover
        # (Sum of absolute trades divided by 2 to get one-sided turnover)
        self.turnover = (w_target - w_drifted).abs().sum(axis = 1) / 2.0
        
        # --- Step 6: Apply Transaction Costs ---
        # The turnover at index `t` is traded at the end of month `t`.
        # Shift the turnover forward by 1 month so the fee penalizes month `t+1`'s return.
        tc_penalty = self.turnover.shift(1).fillna(0.0) * self.tc_decimal
        
        # Calculate the Net Portfolio Return
        self.performance['net_port_ret'] = self.performance['port_ret'] - tc_penalty
        
        # Re-calculate the Cumulative Wealth Index using Net Returns
        self.performance['cum_port'] = (1 + self.performance['net_port_ret']).cumprod()

        return performance 
        """
    
    def generate_tearsheet(self):
        """
        Calculates and prints performance report.
        """
        stats = self.performance.copy()
        ANN = 12 # Annualization Factor (Monthly Data)
        
        # 1. Total Return (Arithmetic Annualized)
        # We use the arithmetic mean here specifically because it is required 
        # for the standard Sharpe Ratio and Information Ratio calculations.
        port_ret_ann = stats['net_port_ret'].mean() * ANN
        bench_ret_ann = stats['bench_ret'].mean() * ANN
        excess_ret_ann = stats['excess_ret'].mean() * ANN 
        active_ret_ann = stats['active_ret'].mean() * ANN
        
        # 1b. True Compound Return (Geometric Annualized / CAGR)
        # This reflects the actual realized growth of a $1 investment over an annual period.
        total_months = len(stats)
        
        final_port_wealth = stats['cum_port'].iloc[-1]
        if final_port_wealth <= 0:
            port_cagr = -1.0 
        else:
            port_cagr = (final_port_wealth ** (ANN / total_months)) - 1.0


        # Handle Benchmark Bankruptcy safely
        final_bench_wealth = stats['cum_bench'].iloc[-1]
        if final_bench_wealth <= 0:
            bench_cagr = -1.0
        else:
            bench_cagr = (final_bench_wealth ** (ANN / total_months)) - 1.0

        if bench_cagr == -1.0 or port_cagr == -1.0:
            active_geometric_ret = np.nan
        else:
            active_geometric_ret = (1 + port_cagr) / (1 + bench_cagr) - 1

        
        # 2. Volatility (Annualized Std Dev)
        # 2. Volatility (Annualized Std Dev)
        port_vol_ann = stats['net_port_ret'].std() * np.sqrt(ANN)
        active_vol_ann = stats['active_ret'].std() * np.sqrt(ANN) # Tracking Error
        excess_vol_ann = stats['excess_ret'].std() * np.sqrt(ANN)

        # 3. Risk-Adjusted Ratios
        # Sharpe = Excess Return / Volatility of Excess Return
        sharpe = excess_ret_ann / excess_vol_ann
        
        # Information Ratio = Active Return / Tracking Error
        ir = active_ret_ann / active_vol_ann
        
        # 4. Max Drawdown
        # Peak-to-Trough decline
        peak = stats['cum_port'].cummax()
        drawdown = (stats['cum_port'] - peak) / peak
        max_dd = drawdown.min()
        
        # 5. Average Turnover
        avg_turnover = self.turnover.mean()
        
        # --- PRINT REPORT ---
        print("\n" + "="*45)
        print(f"{'BACKTEST PERFORMANCE REPORT':^45}")
        print("="*45)
        print(f"Compound Return (CAGR):     {port_cagr:.2%}")
        print(f"Benchmark CAGR:             {bench_cagr:.2%}")
        print(f"Geometric Active Return:    {active_geometric_ret:.2%}")
        print("-" * 45)
        print(f"Arithmetic Ann. Return:     {port_ret_ann:.2%}")
        print(f"Arithmetic Bench. Return:   {bench_ret_ann:.2%}")
        print(f"Arithmetic Active Return:   {active_ret_ann:.2%}")
        print("-" * 45)
        print(f"Portfolio Volatility:       {port_vol_ann:.2%}")
        print(f"Tracking Error:             {active_vol_ann:.2%}")
        print("-" * 45)
        print(f"Sharpe Ratio (Rf adj):      {sharpe:.2f}")
        print(f"Information Ratio:          {ir:.2f}")
        print("-" * 45)
        print(f"Max Drawdown:               {max_dd:.2%}")
        print(f"Avg Monthly Turnover:       {avg_turnover:.2%}")
        print("="*45)
        
        filename = os.path.basename(self.holding_path)        
        
        # Save summary metrics with dynamic name
        run_id = filename.replace('holdings_', '').replace('.parquet', '')        
        
        # Save summary metrics with dynamic Run ID
        save_path = os.path.join(self.backtest_output_path, f'backtest_metrics_{run_id}.csv')        
        
        # Add the new metrics and name the Series for a clean CSV header
        metrics = pd.Series({
            'CAGR': port_cagr,
            'Bench CAGR': bench_cagr,
            'Geo Active Ret': active_geometric_ret,
            'Arith Ann Ret': port_ret_ann,
            'Arith Bench Ret': bench_ret_ann,
            'Arith Active Ret': active_ret_ann,
            'Port Volatility': port_vol_ann,
            'Tracking Error': active_vol_ann,
            'Sharpe': sharpe,
            'IR': ir,
            'Max DD': max_dd,
            'Turnover': avg_turnover
        }, name='Value')
        
        metrics.index.name = 'Metric'
        metrics.to_csv(save_path)
        
        # Save Full Equity Curve with dynamic Run ID
        curve_path = os.path.join(self.backtest_output_path, f'equity_curve_{run_id}.csv')
        self.performance.to_csv(curve_path)
        
        print(f"Results saved to {self.backtest_output_path} with Run ID: {run_id}")
    
    def run_backtest_process(self):
        self.load_data()
        self.run_backtest()
        self.generate_tearsheet()


if __name__ == "__main__":
    pass